### ISSUE TITLE
🐛 Project Scroll not working properly 😢

### ISSUE THREAD

**Issue by sachin-duhan26** [sachin-duhan26/sachin-duhan26.github.io#2]

**Comment by danielochka** [comment]
Hello, can you tell me more about your problem?

**Comment by sachin-duhan26** [comment]
Hello @danielochka ,
When you visit [sachinduhan.me](https://sachinduhan.me/#projects) and scroll down to the Projects section. You will find the projects section and you change the projects some unexpected behavior can be seen.

List of issues - 
1. CSS styles are not getting applied properly when we change projects.
2. only 4 projects can be seen, HTML file (index.html), even though contains 5 projects.

Can you recommend some solution or way around for the same?
Thanks
